language: python
python:
  # - "2.6"
  - "2.7"
  # - "3.2"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  #- "pypy"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m unittest discover -s ./tests --verbose

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e12bddb5272997bd3ee9
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: change     # options: [always|never|change] default: always

after_success:
  - bash <(curl -s https://codecov.io/bash)
